---
- hosts: localhost
  tasks:
    - name: Installing Apache2 package
      package:
        name: apache2
        state: present
    - name: Starting Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
