---
- hosts: localhost
  tasks:
    - name: Update all packages to the latest version
      apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"
      become: true
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"
      become: true
    - name: Install python3-pip
      package:
        name: python3-pip
      when: ansible_facts['os_family'] == "Debian"
      become: true
