---
- hosts: localhost
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"
    - name: Install software-properties-common
      package:
        name: software-properties-common
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Add repository
      apt_repository:
        repo: ppa:deadsnakes/ppa 
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Again Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"
    - name: Install python3.7
      package:
        name: python3.7
        state: present
      when: ansible_facts['os_family'] == "Debian"
